/** Declaration file generated by dts-gen */

export = opossum;

declare function opossum(action: any, options: any): any;

declare namespace opossum {
    const prototype: {
    };

    function promisify(func: any, ...args: any[]): any;

    namespace promisify {
        const prototype: {
        };

    }

}

