/** Declaration file generated by dts-gen */

declare module "node-cron" {
    export function schedule(expression: any, func: any, immediateStart: any): any;

    export function validate(expression: any): any;

    export namespace schedule {
        const prototype: {
        };

    }

    export namespace validate {
        const prototype: {
        };

    }
}