/** Declaration file generated by dts-gen */

declare module "circuit-retry" {
    export function delay(duration: any): any;
    export namespace delay {
        const prototype: {
        };
    }
}

